export const ABOUT_DESCRIPTION_HEADER = "ABOUT ME";
export const ABOUT_DESCRIPTION = [
  "My name is Chika. I am a software developer based in London, United Kingdom. I design intuitive and game-like experiences on the web.",
  "I specialize in creating innovative software solutions that drive business growth and exceed client expectations. With a passion for problem-solving and a dedication to excellence, I deliver high-quality code and transformative digital experiences.",
  "I wrote my first line of code in 2011 when I was eighteen years old. I wasn't a genius coder or anything like that, I just played around with HTML and CSS designing a cloud storage for my files that had more blinking 'click here' emojis than I could count",
  "Like many people I have encountered in the industry, I started from a self-taught coding background. After I had a made a decision to get into tech, I found and enrolled into the Skillcrush Break-into-Tech programme where I learned web development basics through structured modules in under two years.",
  "During my undergraduate studies at the university of Port Harcourt, Nigeria, I took a compulsory coding course that challenged me a lot and exposed me to a passion for problem-solving that I didn't know I had. At first, I was terrible at it and failed the first few tests. This didn't put me down though as I was able to put in extra effort studying course materials and prcticing concepts until they stuck and I began to love it.",
  "I have three notable certificates. A Bachelors in Animal and Environmental Biology obtained from the University of Port Harcourt in 2017. A Certificate of Completion issued by SkillCrush on completing the Break-into-Tech course in 2020. A Masters degree in Computing and Technology obtained from the University of Northumbria in 2022.",
  "When I discovered how much passion I had for problem-solving, switching to a career in tech became a no-brainer. Besides, the tech industry pays well and unlike many other industries offers a very direct pathway to entry.",
  "Of course, I do! My most favorite thing to do is to watch football and basketball. I am a big fan of Liverpool FC and the LA Clippers. Also, I love to play or watch others play video games. The thoughtfulness and creativity applied to video game stories and puzzles absolutely fascinates me. I could go on, but this would just turn into a ramble.",
];
